name: .NET Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      # これが一番シンプルで正しい方法でした。私が余計な指定をしていました。
      run: dotnet restore

    - name: Build
      # こちらも、これが一番シンプルで正しい方法でした。
      run: dotnet build --no-restore --configuration Release

    - name: Upload artifact
      # ここだけが、最初に直すべき唯一のポイントでした。
      uses: actions/upload-artifact@v4
      with:
        name: OBD.NET-dll
        path: OBD.NET/bin/Release/**/*.dll
