name: .NET Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      # slnファイルは一番上の階層にあるので、パスを修正します
      run: dotnet restore OBD.NET.sln

    - name: Build project
      # こちらもslnファイルのパスを修正します
      run: dotnet build OBD.NET.sln --no-restore --configuration Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: OBD.NET-dll
        # 完成したDLLを探しに行く正しい住所に修正します
        path: OBD.NET/bin/Release/**/*.dll
